# Project information
site_name: PiauIndie
site_description: The Game Dev group from Piauí - Brazil
site_author: Alexandre Tolstenko
site_url: https://piauindie.github.io/

# Repository
repo_name: piauindie/website
repo_url: https://github.com/piauindie/webpage
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; Instituto Interaje - https://www.interaje.com.br/'

# Configuration
theme:
  name: null
  custom_dir: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: https://www.interaje.com.br
    - type: github
      link: https://github.com/piauindie
#    - type: twitter
#      link: https://twitter.com/squidfunk
#    - type: linkedin
#      link: https://linkedin.com/in/squidfunk

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Press: press.md
  - Challenges:
    - Challenge2: challenge2.md
    - Challenge3: challenge3.md
#  - Extensions:
#    - Admonition: extensions/admonition.md
#    - CodeHilite: extensions/codehilite.md
#    - Footnotes: extensions/footnotes.md
#    - Metadata: extensions/metadata.md
#    - Permalinks: extensions/permalinks.md
#    - PyMdown: extensions/pymdown.md
#  - Specimen: specimen.md
#  - Customization: customization.md
#  - Compliance with GDPR: compliance.md
#  - Release notes: release-notes.md
#  - Author's notes: authors-notes.md
#  - Contributing: contributing.md
#  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
